### ISSUE TITLE
Nothing loads

### ISSUE THREAD

**Issue by HimbeersaftLP** [simonnorberg/klingar#1]
After signing in I just get presented a blank page with the upper menubar and three dots in there.

**Comment by simonnorberg** [comment]
Do you have a Music type library on your Plex server?

**Comment by HimbeersaftLP** [comment]
Yup

**Comment by simonnorberg** [comment]
Ok, I'll try to reproduce it. Any information about your server configuration would be helpful.

**Comment by HimbeersaftLP** [comment]
I was running server version 1.15.3.876. My music library is called "Musik", the library language is German and most songs are opus and m4a files.
I hope that helps.

**Comment by HimbeersaftLP** [comment]
Also occurs on server 1.15.4.993

**Comment by indrora** [comment]
Seeing this when on local wifi. 

Not seeing it when on cellular. 

This seems to be that you're picking the first non-local server, which in this case means that if your router drops packets from the inside to the external IP, nothing loads.

**Comment by HimbeersaftLP** [comment]
The issue was, that I had disabled remote access, it worked after I enabled it.

Does this app now support playlists?
