### ISSUE TITLE
Black screen in main page

### ISSUE THREAD

**Issue by bisrinursa** [simonnorberg/klingar#2]
I'm using below configuration:
IDE: Android studio 3.5
Branch: latest master branch after commit #https://github.com/simonnorberg/klingar/commit/e5be6bac771f9145a32056a5577e66888a88b40c was merged. 
Device: Emulator 6.0

![Screen Shot 2019-09-23 at 16 17 10](https://user-images.githubusercontent.com/3761901/65414620-4d5f7f00-de1e-11e9-9b73-c51a41df8e7f.png)
The app always shows blank screen like above screenshot. It seems observer `onNext` and `onError` isn't called
![Screen Shot 2019-09-23 at 16 15 04](https://user-images.githubusercontent.com/3761901/65414618-4cc6e880-de1e-11e9-98c7-cd90d26f8ad3.png)

Could you help me what should I do to show the content instead?

**Comment by simonnorberg** [comment]
Is Remote Access enabled in your Plex server?

**Comment by bisrinursa** [comment]
I see. I don't have my own Plex server. I thought the API itself is provided by the developer(in this case you as the developer), therefore any developers who downloaded or cloned this repo could run and test this app easily. BTW, is there a way to open and give access a Plex server to developers who wants to run and test the app, @simonnorberg ?

**Comment by simonnorberg** [comment]
No, Klingar is just a client. How you get access to a [Plex server](https://www.plex.tv/media-server-downloads/#plex-media-server) is up to you.

**Comment by bisrinursa** [comment]
Thanks in advance @simonnorberg
