### ISSUE TITLE
No longer on Google Play / Under active development?

### ISSUE THREAD

**Issue by jason0x21** [simonnorberg/klingar#3]
Is this player still being developed?  I noticed it was once on Google Play, but no longer. There's a lot of traffic on the Plex forums about how terrible the current Plex Android app is for music, and particularly Android Auto, and if this works even marginally better than the default app, I'd like to see it back in the store.  How can I help?

**Comment by simonnorberg** [comment]
This player is no longer maintained and is therefore not available on Google Play.
